// <auto-generated />
namespace ServerChatsApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v5_chatsapp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v5_chatsapp));
        
        string IMigrationMetadata.Id
        {
            get { return "202003100739112_v5_chatsapp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
